language: ruby
rvm:
- 2.3.0
before_install:
  - rm Gemfile.lock
  - gem update
  - gem install bundler
  - chmod u+x bin/rails
script:
  - ruby bin/rails db:migrate RAILS_ENV=test
  - ruby bin/rails test